name: sollight
gnome: ":6c28978a-af78-434e-a97f-b5c252a080fd/"
terminal: Solarized Light
mintty: solarized-light.minttyrc
tmux: solarized-light_tmux
vim: solarized-light_vim
zsh: solarized-light
bat: Solarized (light)
firefox: "{71864fba-a0ac-47f5-a514-e5f3378b9c12}"
vscode: "Solarized Light"
alias:
  - light
  - sollight
  - day
