name: soldark
gnome: ":6c28978a-af78-434e-a97f-b5c252a080fd"
terminal: Solarized Dark
mintty: solarized-dark.minttyrc
tmux: solarized-dark_tmux
vim: solarized-dark_vim
zsh: solarized-dark
bat: Solarized (dark)
alias:
  - dark
  - soldark
  - test
