#!/bin/zsh
# 30/08/2018 update - will only switch to a branch if
# provided as first argument; will warn if changes
usage="$(basename "$0") If given an argument, tries to switch to that branch. Then, uses NVM to install NPM, then determines if yarn or npm should be used to start. Starts server logging to server.log in folder where run."

nolog=false

while getopts ':hn' option; do
  case "$option" in
    h) echo "$usage"
       exit
       ;;
    n) nolog=true
      ;;
  esac
done
shift $((OPTIND -1))

#Setup NVM
export NVM_DIR="$HOME/.nvm"
. "/usr/local/opt/nvm/nvm.sh"

changes=$(git diff --name-only)
if [ -n "$1" ] ; then
  if [ -n "$changes" ] ; then
    read "nuke?You have local changes; Nuke 'em? (y): "
  fi
  if [ -z "$nuke" ] || [ "$nuke" = "y" ] || [ "$nuke" = "yes" ] ; then
    if [ -n "$changes" ] ; then
      git reset --hard
    fi
    git checkout $1
    git pull
  fi
else
  if [ -z "$changes" ] ; then
    git pull
  fi
fi

nvm install
files=$(ls)
if [[ "$files" == *"yarn"* ]] ; then
  yarn install
  if $nolog ; then
    yarn dev
  else
    echo "\033[0;31mrun 'less +F server.log' to see the log.\033[0m"
    yarn dev > server.log 2>&1
  fi
else
  npm install
  scripts=$(npm run)
   if [[ $scripts =~ '[[:space:]]+dev[[:space:]]+' ]] ; then
     if $nolog ; then
       npm run dev
     else
      echo "\033[0;31mrun 'less +F server.log' to see the log.\033[0m"
      npm run dev > server.log 2>&1
    fi
  else
    if $nolog ; then
      npm start
    else
      echo "\033[0;31mrun 'less +F server.log' to see the log.\033[0m"
      npm start > server.log 2>&1 
    fi
  fi
fi

